### ISSUE TITLE
Question about ANTSUseDeformationFieldToGetAffineTransform

### ISSUE THREAD

**Issue by estellenassar** [CoBrALab/twolevel_ants_dbm#54]
Hello,

I am new to ANTs, and I have a question about how you generate your **relative** jacobian. Mainly, I am not quite sure how the `ANTSUseDeformationFieldToGetAffineTransform` function works.

Going through your code, I see that you first input the registration Warp field into `ANTSUseDeformationFieldToGetAffineTransform` and obtain a delin.mat file as output - I assume this represents the affine residuals. The issue is that the Warp field is _"the diffeomorphic transformation pulling the affine transformed moving image toward the fixed image"_ (ANTs documentation), so should **only** contain transformations from the deformable SyN step of the registration. Hence I wonder how affine residuals are being extracted - maybe this is a question for the ANTs developers?

I also want to make sure I understand what happens to delin.mat when you input it into `antsApplyTransforms`. Am I right in saying that you essentially transform the delin matrix into a composite delin field that is mapping toward your template space? This would make sense.

Next, I understand that you use `CreateJacobianDeterminantImage` to extract the log jacobian determinants: the nlin jacobian from the registration Warp field, and the delin jacobian from the previously derived delin composite field.

Finally, you add both jacobians together using `ImageMath` to create the relative jacobian. I know that you want to remove the affine residuals from nlin, but I understand that since the delin jacobian maps from subject to template, whereas the nlin jacobian maps from template to subject, adding them together is equivalent to removing delin from nlin.

My main issue is understanding how `ANTSUseDeformationFieldToGetAffineTransform` works, but please let me know if I am correct in my explanations.

Thank you!

**Comment by gdevenyi** [comment]
Hi, here's my best attempt at answering.

> Going through your code, I see that you first input the registration Warp field into ANTSUseDeformationFieldToGetAffineTransform and obtain a delin.mat file as output - I assume this represents the affine residuals.

So, ANTSUseDeformationFieldToGetAffineTransform doesn't get "residuals" it simply estimates an affine transformation which represents the best fit from transforming a bunch of points by the non-linear warp field. I conceptually consider this to be a "residual" affine for the purposes of a DBM.

>  so should only contain transformations from the deformable SyN step of the registration. Hence I wonder how affine residuals are being extracted - maybe this is a question for the ANTs developers?

Consider the following hypothetical example:
A "fixed" image which is a typical healthy brain, and a "moving" image which is a brain with very large ventricles, both extracted from their skulls. The *affine* registration between these two brains will end up being a halfway compromise between matching the brain edges (a strong signal) and the ventricular edges (another strong signal). Now, we start the non-linear registration, and the low-resolution stages end up providing some large deformations to align both the brain edge and the ventricular edge, before doing the fine alignment. This large deformation is akin to a sort of affine if we consider just the brain tissue (rather than the ventricular volume). This is the point of the ``ANTSUseDeformationFieldToGetAffineTransform``, it scatters points inside a mask, applies the warp field, and then estimates the affine that would approximate those points.

>  I also want to make sure I understand what happens to delin.mat when you input it into antsApplyTransforms. Am I right in saying that you essentially transform the delin matrix into a composite delin field that is mapping toward your template space? This would make sense.

Close, I use [delin.mat,1] which is the inverse affine, I want to *remove* the affine component of the Warp field, which means I need to compute the Jacobian of the inverse transform, hence the inverse here.

> Next, I understand that you use CreateJacobianDeterminantImage to extract the log jacobian determinants: the nlin jacobian from the registration Warp field, and the delin jacobian from the previously derived delin composite field.

Correct

> Finally, you add both jacobians together using ImageMath to create the relative jacobian. I know that you want to remove the affine residuals from nlin, but I understand that since the delin jacobian maps from subject to template, whereas the nlin jacobian maps from template to subject, adding them together is equivalent to removing delin from nlin.

Again correct.

Hopefully this helps. Happy to answer more questions.

**Comment by estellenassar** [comment]
Thank you Gabriel, that cleared everything up!
